---
- name: Yum - add Icinga repository (stable)
  ansible.builtin.yum_repository:
    file: /etc/yum.repos.d/ICINGA-release
    name: icinga-stable-release
    description: "{{ icinga_repo_yum_stable_description }}"
    baseurl: "{{ icinga_repo_yum_stable_url }}"
    gpgkey: "{{ icinga_repo_yum_stable_key }}"
    gpgcheck: yes
    enabled: "{{ icinga_repo_stable }}"
    username: "{{ icinga_repo_subscription_username | default(omit) }}"
    password: "{{ icinga_repo_subscription_password | default(omit) }}"

- name: Yum - add Icinga repository (testing)
  ansible.builtin.yum_repository:
    file: /etc/yum.repos.d/ICINGA-testing
    name: icinga-testing-builds
    description: "{{ icinga_repo_yum_testing_description }}"
    baseurl: "{{ icinga_repo_yum_testing_url }}"
    gpgkey: "{{ icinga_repo_yum_testing_key }}"
    gpgcheck: yes
    enabled: "{{ icinga_repo_testing }}"
    username: "{{ icinga_repo_subscription_username | default(omit) }}"
    password: "{{ icinga_repo_subscription_password | default(omit) }}"

- name: Yum - add Icinga repository (snapshot)
  ansible.builtin.yum_repository:
    file: /etc/yum.repos.d/ICINGA-snapshot
    name: icinga-snapshot-builds
    description: "{{ icinga_repo_yum_snapshot_description }}"
    baseurl: "{{ icinga_repo_yum_snapshot_url }}"
    gpgkey: "{{ icinga_repo_yum_snapshot_key }}"
    gpgcheck: yes
    enabled: "{{ icinga_repo_snapshot }}"
    username: "{{ icinga_repo_subscription_username | default(omit) }}"
    password: "{{ icinga_repo_subscription_password | default(omit) }}"

- name: Yum - add NETWAYS Extras repository
  ansible.builtin.yum_repository:
    name: "netways-extras"
    description: "{{ netways_repo_extras_yum_description }}"
    baseurl: "{{ netways_repo_extras_yum_url }}"
    gpgkey: "{{ netways_repo_extras_yum_key }}"
    gpgcheck: true
    enabled: "{{ netways_repo_extras }}"

- name: Yum - add NETWAYS Plugins repository
  ansible.builtin.yum_repository:
    name: "netways-plugins"
    description: "{{ netways_repo_plugins_yum_description }}"
    baseurl: "{{ netways_repo_plugins_yum_url }}"
    gpgkey: "{{ netways_repo_plugins_yum_key }}"
    gpgcheck: true
    enabled: "{{ netways_repo_plugins }}"

- name: Yum - add EPEL repository
  yum:
    name: "{{ icinga_repo_epel_package_name }}"
    state: present
  when: icinga_repo_epel|bool == true

- name: Yum - add SCL repositories
  yum:
    name: centos-release-scl
    state: present
  when:
    - icinga_repo_scl|bool == true
    - ansible_facts["distribution"] == "CentOS"
    - ansible_facts["distribution_major_version"] < "8"
