---
icingaweb2_module_packages:
  icingadb: icingadb-web
  director: icinga-director
  graphite: icinga-graphite-web
  x509: icinga-x509
  businessprocess: icinga-businessprocess
  kubernetes: icinga-kubernetes-web
  monitoring: icingaweb2
  doc: icingaweb2
  migrate: icingaweb2
  setup: icingaweb2
  translation: icingaweb2
  perfdatagraphs: icingaweb2-module-perfdatagraphs
  perfdatagraphsgraphite: icingaweb2-module-perfdatagraphs-graphite
  perfdatagraphsinfluxdbv1: icingaweb2-module-perfdatagraphs-influxdbv1
  perfdatagraphsinfluxdbv2: icingaweb2-module-perfdatagraphs-influxdbv2
